# Generated by Django 5.0.3 on 2024-05-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='text',
        ),
    ]
