# Generated by Django 5.0.3 on 2024-05-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signup_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
