# Generated by Django 5.0.3 on 2024-05-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0004_profile_signup_password_profile_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
